http:
  routers:
    auth-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/auth`)"
      entryPoints:
        - web
      service: auth-service

    user-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/users`)"
      entryPoints:
        - web
      service: user-service

    device-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/devices`)"
      entryPoints:
        - web
      service: device-service

    userlocal-router:
      rule: "Host(`localhost`) && PathPrefix(`/api/users-local`)"
      entryPoints:
        - web
      service: device-service

  services:
    auth-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://host.docker.internal:8083/"

    user-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://host.docker.internal:8081/"

    device-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://host.docker.internal:8082/"
